if: commit_message !~ /auto\/ci:\sset\sversion/
language: node_js
node_js:
  - "12.16.3"
git:
  depth: false
cache:
  directories:
    - node_modules
script:
  - git remote set-url origin https://$USER:$GITHUB_API_KEY@github.com/eigen-space/react-test-utils.git
  - yarn lint && yarn build:package && yarn test:ci && npm run deploy:publish;
before_install:
  - echo "registry=https://$REGISTRY/" >> .npmrc
  - echo "//$REGISTRY/:_authToken=$ACCESS_TOKEN" >> .npmrc
